### ISSUE TITLE
bezierlanenet_culane  question

### ISSUE THREAD

**Issue by miao02830** [voldemortX/pytorch-auto-drive#101]
I have trained the bezierlanenet model and got the weights.  
![image](https://user-images.githubusercontent.com/27732256/175262767-1cb1b0f8-bdf3-4fb7-9c88-21374e87708e.png)
Then I ran the test command and got the dir:
![image](https://user-images.githubusercontent.com/27732256/175263046-15073569-212d-4c61-9919-dc751cb4a809.png)
but when i ran the command ./autotest_culane.sh resnet34_bezierlanenet_culane-aug1b test checkpoints,i meet the problems
When did you generate this file in output ?ths!

**Comment by voldemortX** [comment]
@miao02830 Hi! What problem did you encounter when using `autotest_culane.sh`, do you have screenshot for it?

**Comment by miao02830** [comment]
but when i ran the command ./autotest_culane.sh resnet34_bezierlanenet_culane-aug1b test checkpoints,i meet the problems
When did you generate this file in output ?ths!

![image](https://user-images.githubusercontent.com/27732256/175269699-abdb026f-93d3-4320-b518-826ecce7fb15.png)

**Comment by voldemortX** [comment]
@miao02830 it seems the error is in `Permission denied`? May be try `chmod 777 eval*` in the tools/culane_evaluation dir.

**Comment by miao02830** [comment]
No, it's not. At first, I didn't use sh to run the command. I have changed it. Now the problem is that there is no such file
![image](https://user-images.githubusercontent.com/27732256/175280832-a0096292-dd4b-4b44-9ba2-d8dcf502c1e0.png)
I would like to ask you when to generate this file ths!

**Comment by voldemortX** [comment]
> No, it's not. At first, I didn't use sh to run the command. I have changed it. Now the problem is that there is no such file
> ![image](https://user-images.githubusercontent.com/27732256/175280832-a0096292-dd4b-4b44-9ba2-d8dcf502c1e0.png)
> I would like to ask you when to generate this file ths!

but that file is generated by eval.sh

**Comment by miao02830** [comment]
thankyou i got it!
