### ISSUE TITLE
UserWarning: Can't complie line nms op for LaneATT. Set verbose=True for load in /utils/csrc/apis.py L9 for details.

### ISSUE THREAD

**Issue by ailias** [voldemortX/pytorch-auto-drive#103]
How to compile line nms using python or pip， why not use laneatt nms installation method?

**Comment by voldemortX** [comment]
We use the installation-free loading mode.  If you can install the laneatt nms package, you should also be able to load this. What was the issue?

**Comment by YaoChengTang** [comment]
In my case, some packages are missing in the cloud server, like pybind11 and ninja. Installing them, removing cache files in '.cache' and '__pycache__', and you may un the code successfully. Hopes it will help you.
