### ISSUE TITLE
About CULane Dataset

### ISSUE THREAD

**Issue by huanFigure** [voldemortX/pytorch-auto-drive#104]
您好！我看到您的论文上的CULane数据集有‘dazzle’类，但是我从CULane网盘上下载的CULane数据集没有这个类，您能说明一下这个类的来源吗

**Comment by voldemortX** [comment]
@huanFigure 有个高曝光的类别一般被叫做dazzle light或者hlight，你看到的类别列表是哪些呢

**Comment by huanFigure** [comment]
看到了，麻烦您了，好多问题一问出来自己就找到答案了，谢谢您了
