### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by liangjxiong** [voldemortX/pytorch-auto-drive#105]
已经在自己制作的数据集训练好了(TuSimple格式)，我想要可视化一张图片的效果图，在RESA模型上，我应该怎么操作？谢谢！

**Comment by voldemortX** [comment]
@liangjxiong 可以把要可视化的图片原图放到一个文件夹里，然后用 https://www.github.com/voldemortX/pytorch-auto-drive/tree/master/docs/VISUALIZATION.md 里面的文件夹lane point可视化方式。建议首先使用--pred模式，比较易用。

**Comment by liangjxiong** [comment]
需要对应的label文件吗？

**Comment by voldemortX** [comment]
> 需要对应的label文件吗？

label有没有都可以

**Comment by liangjxiong** [comment]
非常感谢您的工作和指导，我已经实现可视化了，谢谢您！我还有一个问题想问，SCNN和RESA模型是基于语义分割的，为什么可视化结果输出一系列点？

**Comment by voldemortX** [comment]
> 非常感谢您的工作和指导，我已经实现可视化了，谢谢您！我还有一个问题想问，SCNN和RESA模型是基于语义分割的，为什么可视化结果输出一系列点？

因为最后评测前或者交给下游任务一般都会经过后处理得到一系列点。所以可视化和统一的车道线输出格式选择了点或线的形式。

但分割的mask标注是支持了可视化的。

**Comment by voldemortX** [comment]
> 分割的mask标注可视化，要怎样执行？我可能最终想要的是这样可视化。

对应图片文件的 `--mask-suffix` 和 `--mask-path` 即可。可以参照 [VISUALIZATION.md](https://www.github.com/voldemortX/pytorch-auto-drive/tree/master/docs/VISUALIZATION.md) 的教程。
