### ISSUE TITLE
About CULane official evaluation function

### ISSUE THREAD

**Issue by huanFigure** [voldemortX/pytorch-auto-drive#106]
Hello,
I have run the enet_baseline model,and I have gotten the result 'checkpoints/enet_baseline_/culane/model.pt'.And then I the test enet_model ,and got the output 'output/driver_*frame/*.MP4/*.lines.txt'.But when I run './tools/culane_evaluation/eval.sh' to evaluate the output files, I got the number 0 or -1
 
![1657105465103](https://user-images.githubusercontent.com/30222662/177536396-b7c6edf3-d78c-4cc2-8915-45a54d078833.png)

Have you ever encountered such a situation? 
And the configuration in eval.sh:
data_dir is the original CULane data which download from website
detect_dir is the output of the test 'python main_landet.py --test --config=configs/lane_detection/baseline/enet_culane.py --mixed-precision'
Is there anything wrong with my configuation?

**Comment by huanFigure** [comment]
And the eval class configuration 'output/out*.txt' ,I copy the downloaded from website CULane to this directory and renamed them
![1657106195351](https://user-images.githubusercontent.com/30222662/177538252-91096d4b-4147-4600-9da1-dc7bfe98a564.png)

**Comment by voldemortX** [comment]
@huanFigure I only encounter this when the model really have 0 accuracy. Did you train the model yourself? Perhaps try testing one of the uploaded checkpoints and verify if the issue is in evaluation script?

**Comment by huanFigure** [comment]
Thanks for your replay. I have solved this problem. The reason is that the file name generated by the test end with '.jpg.lines.txt' which doesn't match  the original file name '.lines.txt'
