### ISSUE TITLE
测试culane数据集的demo

### ISSUE THREAD

**Issue by GongDianCheng** [voldemortX/pytorch-auto-drive#109]
感谢您的开源，被文章中提出的贝塞尔曲线拟合吸引过来的。在尝试测试culane数据集时，执行如下脚本：
`python main_landet.py --test --config=configs/lane_detection/bezierlanenet/resnet34_culane_aug1b.py 
 --checkpoint=resnet34_bezierlanenet_culane_aug1b_20211109.pt 
`
然而得到的输出是test_cfg.json,并不是数据集的测试结果，
请问我的脚本有问题吗，我是不是忽略了哪些关键点

**Comment by voldemortX** [comment]
@GongDianCheng 可以看一下 https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/LANEDETECTION.md

如果要测数据集的F-1结果，需要autotest_culane.sh
如果要预测的*lines.txt文件的话，它们会出现在缓存文件夹./output

**Comment by GongDianCheng** [comment]
您好，感谢您的回复！
我注意到了有一个步骤mkdir output ，我创建了该文件夹，但是运行那个问题所述命令后，output下没有结果，这也是我疑惑的地方

**Comment by GongDianCheng** [comment]
> @GongDianCheng 可以看一下 https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/LANEDETECTION.md
> 
> 如果要测数据集的F-1结果，需要autotest_culane.sh 如果要预测的*lines.txt文件的话，它们会出现在缓存文件夹./output

您好，感谢您的回复！
我注意到了有一个步骤mkdir output ，我创建了该文件夹，但是运行那个问题所述命令后，output下没有结果，这也是我疑惑的地方

**Comment by voldemortX** [comment]
这有点奇怪，你运行main_landet.py的时候有输出和报错信息么。

**Comment by GongDianCheng** [comment]
> 这有点奇怪，你运行main_landet.py的时候有输出和报错信息么。

`(torch1.9) gdc@gdc:~/gong/lane-detection/pytorch-auto-drive-master$ python main_landet.py --test --config=configs/lane_detection/bezierlanenet/resnet34_culane_aug1b.py  --checkpoint=resnet34_bezierlanenet_culane_aug1b_20211109.pt 
Successfully complied line nms for LaneATT.
Loaded torchvision ImageNet pre-trained weights V1.
cuda:0
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.92it/s]
Files saved at: ./checkpoints/resnet34_bezierlanenet_culane-aug2.
Tensorboard log at: ./checkpoints/tb_logs/resnet34_bezierlanenet_culane-aug2
`

**Comment by GongDianCheng** [comment]
> 这有点奇怪，你运行main_landet.py的时候有输出和报错信息么。

`(torch1.9) gdc@gdc:~/gong/lane-detection/pytorch-auto-drive-master$ python main_landet.py  --test 
--config=configs/lane_detection/bezierlanenet/resnet34_culane_aug1b.py  
--checkpoint=resnet34_bezierlanenet_culane_aug1b_20211109.pt 
Successfully complied line nms for LaneATT.
Loaded torchvision ImageNet pre-trained weights V1.
cuda:0
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.92it/s]
Files saved at: ./checkpoints/resnet34_bezierlanenet_culane-aug2.
Tensorboard log at: ./checkpoints/tb_logs/resnet34_bezierlanenet_culane-aug2
`

**Comment by GongDianCheng** [comment]
![2022-07-13 10-40-18 的屏幕截图](https://user-images.githubusercontent.com/31959379/178639586-ac403667-da13-4a4c-83b8-5e34a8f0e2cb.png)

**Comment by voldemortX** [comment]
@GongDianCheng 你的测试是几秒钟就完成了么，测试集应该有上万张图，确认一下数据集有没有问题？

**Comment by GongDianCheng** [comment]
> 

是这样的，我修改了culane的test.list，只包含了几张图片，想看一下论文中的测试效果

**Comment by voldemortX** [comment]
https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/datasets/CULANE.md

**Comment by voldemortX** [comment]
> > 
> 
> 是这样的，我修改了culane的test.list，只包含了几张图片，想看一下论文中的测试效果

额，那修改前的测试也有这个问题么

**Comment by voldemortX** [comment]
@GongDianCheng 如果只想看几张图的效果的话，可以放到一个文件夹里直接跑可视化：
https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/VISUALIZATION.md#lane-points-image-folder

**Comment by GongDianCheng** [comment]
@voldemortX 我在测试以下，感谢回复

**Comment by GongDianCheng** [comment]
感谢您提供的idea，问题已解决，应该是我数据集的问题。这是一个伟大全面的自动驾驶框架，感谢开源精神！

**Comment by voldemortX** [comment]
> 感谢您提供的idea，问题已解决，应该是我数据集的问题。这是一个伟大全面的自动驾驶框架，感谢开源精神！

群众的支持是我们前进的动力！

**Comment by Hzy98** [comment]
> 

你好，我想获得测试数据集的f1结果，并且按照CULANE.md中准备python评估脚本，autotest_culane.sh也改为了python。eval.sh和eval_validation.sh中data_dir也都已修改了。但是在执行：./autotest_culane.sh resnet18_bezierlanenet_culane-aug1b test checkpoints还是报错了：
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/25c35859-fdce-45c3-9a11-4e1155fbfb6b)
我的output文件夹中包含测试预测的车道线点：
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/ea1c1157-4e42-4128-89ac-312df8b6eb33)
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/2f2b8093-f29d-4934-ac04-4368b8fac321)

**Comment by voldemortX** [comment]
@Hzy98 看起来是opencv问题，你是开了python后端了吗？

**Comment by Hzy98** [comment]
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/39ec09d8-c3d4-4976-8861-30281051e570)
根据CULANE.md里说的，我只是把autotest_culane.sh中backend修改为了python，别的没有改动。
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/4d9c5587-def0-4b60-962a-b2da2a35bdc5)

**Comment by voldemortX** [comment]
> ![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/39ec09d8-c3d4-4976-8861-30281051e570)
> 根据CULANE.md里说的，我只是把autotest_culane.sh中backend修改为了python，别的没有改动。
> ![image](https://github.com/voldemortX/pytorch-auto-drive/assets/77539868/4d9c5587-def0-4b60-962a-b2da2a35bdc5)
> 

@Hzy98 最顶上改了就行，if里面别改呀。。。

**Comment by Hzy98** [comment]
> > ![image](https://user-images.githubusercontent.com/77539868/237546200-39ec09d8-c3d4-4976-8861-30281051e570.png)
> > 根据CULANE.md里说的，我只是把autotest_culane.sh中backend修改为了python，别的没有改动。
> > ![image](https://user-images.githubusercontent.com/77539868/237546235-4d9c5587-def0-4b60-962a-b2da2a35bdc5.png)
> 
> @Hzy98 最顶上改了就行，if里面别改呀。。。
/

**Comment by Hzy98** [comment]
> 
哦哦 好的 谢谢

**Comment by Hzy98** [comment]
> > ![image](https://user-images.githubusercontent.com/77539868/237546200-39ec09d8-c3d4-4976-8861-30281051e570.png)
> > 根据CULANE.md里说的，我只是把autotest_culane.sh中backend修改为了python，别的没有改动。
> > ![image](https://user-images.githubusercontent.com/77539868/237546235-4d9c5587-def0-4b60-962a-b2da2a35bdc5.png)
> 
> @Hzy98 最顶上改了就行，if里面别改呀。。。

哦哦  我都忘了改了if里面的了，以为只改了我圈出来的地方。谢谢。
