### ISSUE TITLE
投影到3D问题

### ISSUE THREAD

**Issue by JiweiMaster** [voldemortX/pytorch-auto-drive#110]
网络输出的车道线，拟合的曲线，可以投影到3D吗？

**Comment by voldemortX** [comment]
@JiweiMaster 2D车道线检测输出的相当于是 uv 坐标，如果有相机参数和深度信息，可以投影到3D。

这里讲了基本的形式：https://zhuanlan.zhihu.com/p/144307108

实际的相机参数矩阵自由度可能更高，比如内参还可以有axis skew，这取决于你的相机模型。

**Comment by voldemortX** [comment]
This issue seems to be addressed. I'll close it for now. Feel free to continue commenting for reopen/open a new one.
