### ISSUE TITLE
about bezier GT

### ISSUE THREAD

**Issue by ccblublu** [voldemortX/pytorch-auto-drive#111]
How can i get the bezier curve GT in custom dataset? will it be published?

**Comment by voldemortX** [comment]
@ccblublu If your custom dataset is already labeled by sample points, you can refer to this documentation: https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/CURVE.md

But you will need to get the [loader](https://github.com/voldemortX/pytorch-auto-drive/blob/7280e135d79b0d3f9c9c57a73293da6bcd3a2bab/tools/curve_fitting_tools/loader.py) working for your dataset. That will depend on how your custom dataset is organized.

Essentially, you need to fit Bézier curves for your GT lines and save them in the json format.

**Comment by voldemortX** [comment]
This issue seems to be addressed. I'll close it for now. Feel free to continue commenting for reopen/open a new one.
