### ISSUE TITLE
Why instance？

### ISSUE THREAD

**Issue by champagne-yellow** [voldemortX/pytorch-auto-drive#120]
Nice work!
Why does lane detection need instance segmentation? Is semantic segmentation not applicable?

**Comment by voldemortX** [comment]
@champagne-yellow Semantic segmentation can also work (In this framework: Baseline, SCNN, RESA), but in a restrictive way, i.e., restricting the max number of lanes by giving them semantic classes. 1 for ego left, 2 for ego right, etc.

**Comment by voldemortX** [comment]
This issue seems to be addressed. I'll close it for now. Feel free to continue commenting for reopen/open a new one.
