### ISSUE TITLE
 visualize the gts only  File: lane_img_dir.py

### ISSUE THREAD

**Issue by shifan-Z** [voldemortX/pytorch-auto-drive#122]
Thanks for posting your excellent code!
I want to visualize the gts of dataset CULane. To use the code, that it seems it is for the inference model. So if I just wanna show the gts, which config file should I provide? It seems the config file must exist.
https://github.com/voldemortX/pytorch-auto-drive/blob/8cc1d30c9aa56ffb947f0a96eff48d8a4175d63c/tools/vis/lane_img_dir.py#L18

**Comment by voldemortX** [comment]
@shifan-Z Any config that uses CULane should suffice. While we only support image folder inputs. So if you want to parse the entire GT structure from a certain dataset, you may refer to [advanced/VISUALIZE_LANE_DATASETS.md](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/advanced/VISUALIZE_LANE_DATASETS.md).

For CULane, you can try [this config](https://github.com/voldemortX/pytorch-auto-drive/blob/master/configs/lane_detection/bezierlanenet/vis_resnet34_culane_aug1b.py)

**Comment by shifan-Z** [comment]
Thank you so much!
