### ISSUE TITLE
Trained LaneATT model

### ISSUE THREAD

**Issue by daeunni** [voldemortX/pytorch-auto-drive#124]
Hi, 
do you have trained LaneATT CUlane & TUSimple models? :)  (like `resnet18s_lstr_culane_20210722.pt`) 
where can I find them in this repo?

**Comment by voldemortX** [comment]
@daeunni LaneATT is currently supported on CULane. You can find the models in `MODEL_ZOO.md`

e.g., resnet18: https://drive.google.com/file/d/17Ve7RiqxHK4aEXOt7MJzycj6mvvrieZ1/view?usp=sharing

For tusimple, there are some technical reproducibility issues: #98

**Comment by voldemortX** [comment]
Remember to download anchors from Tabelini's repo: https://github.com/voldemortX/pytorch-auto-drive/blob/8cc1d30c9aa56ffb947f0a96eff48d8a4175d63c/configs/lane_detection/laneatt/resnet18_culane.py#L141

**Comment by daeunni** [comment]
Thanks a lot! :) 

btw, I encountered this error. How can I compile `line_nms` ? 
`NameError: name 'line_nms' is not defined`

I tried https://github.com/voldemortX/pytorch-auto-drive/issues/103 method but I can't install the laneatt nms packages.

**Comment by voldemortX** [comment]
@daeunni You mean even the install-mode nms in LaneATT repo can't be installed? Perhaps use `verbose=True`  [here](https://github.com/voldemortX/pytorch-auto-drive/blob/8cc1d30c9aa56ffb947f0a96eff48d8a4175d63c/utils/csrc/apis.py#L9) and see if there is a compiling issue?

**Comment by daeunni** [comment]
Ohh yes ! After I searched some compile error about install-mode nms, I found there was a Ninja error like below. 
`RuntimeError: Ninja is required to load C++ extension`

So I solved that problem using this. It will be helpful to someone ! :3 (It's also related to #103) 
```
wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
sudo unzip ninja-linux.zip -d /usr/local/bin/
sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 
```

**Comment by voldemortX** [comment]
@daeunni Thanks for the solution! Does pip install ninja work?

**Comment by daeunni** [comment]
Yep that works for me

**Comment by voldemortX** [comment]
Well. I think it may be time to add ninja to `requirements.txt`.
