### ISSUE TITLE
cannot identify image file  'culane/test/00004.png.lines.txt'

### ISSUE THREAD

**Issue by Transcients** [voldemortX/pytorch-auto-drive#127]
Thanks for posting your excellent code!
When I wanted to predict directly on a few of my own pictures, I meet the issue:
_PIL.UnidentifiedImageError: cannot identify image file ' culane/test/00004.png.lines.txt'._ 

Howerver, there is no '*.lines.txt'files in my folder.I don't understand why this is happening.My source code is:

_CUDA_VISIBLE_DEVICES=1 python ./tools/vis/lane_img_dir.py --image-path=/culane/test --image-suffix=.png --save-path=/culane/test_result --pred --config=configs/lane_detection/baseline/resnet101_culane.py --checkpoint=/configs/lane_detection/baseline/resnet101_baseline_culane_20210312.pt_ 

I would appreciate it if you can help me solve this problem

**Comment by voldemortX** [comment]
@Transcients Let me try reproduce this. Can you provide your `culane/test` folder's filenames?

**Comment by Transcients** [comment]
OHHHHHHHH, it looks like I generated these '*.line.txt' files while running other programs. I'll delete them and try it again. Thanks!

**Comment by voldemortX** [comment]
> OHHHHHHHH, it looks like I generated these '*.line.txt' files while running other programs. I'll delete them and try it again. Thanks!

hhhhh
