### ISSUE TITLE
Problem of make for Preparing evaluation scripts

### ISSUE THREAD

**Issue by kogakuryo** [voldemortX/pytorch-auto-drive#128]
Hello
I'm having trouble with make in  CULane dataset when preparing the evaluation script.
I use opencv4.5.3 on anaconda.
Previously an error by "error opencv2/core/core.hpp : No such file or directory" was resolved by adding CXXFLAGS += -I/home/username/anaconda3/envs/pad/include/opencv4 to Makefile as you said on https://github.com/voldemortX/pytorch-auto-drive/issues/80.

However, when I make, I get a new error:

CXX/LD evaluate
/usr/bin/ld: -lopencv_core が見つかりません　　←"が見つかりません" means " is not found".
/usr/bin/ld: -lopencv_highgui が見つかりません
/usr/bin/ld: -lopencv_imgproc が見つかりません
/usr/bin/ld: -lopencv_imgcodecs が見つかりません
collect2: error: ld returned 1 exit status
make: *** [Makefile:46: evaluate] error 1

Does the reference in /usr/bin/ld mean that installing opencv in anaconda won't work?

**Comment by voldemortX** [comment]
@kogakuryo what do you mean by installing opencv on anaconda? Is it opencv or opencv-python?

**Comment by kogakuryo** [comment]
I installed not opencv-python but opencv by `conda install ...`

**Comment by voldemortX** [comment]
> I installed not opencv-python but opencv by `conda install ...`

I never tried this method.  Maybe you need to set some environment variables?

**Comment by kogakuryo** [comment]
I see. 
Does that mean you have python, CUDA etc installed on anaconda as on INSTALL.md but not opencv on anaconda?

**Comment by voldemortX** [comment]
> I see. 
> Does that mean you have python, CUDA etc installed on anaconda as on INSTALL.md but not opencv on anaconda?

Yes, my opencv is a seperate installation.

**Comment by kogakuryo** [comment]
thank you for your kindness.
I'll try again from the beginning

**Comment by voldemortX** [comment]
Closed inactive issue.

@kogakuryo Feel free to comment if the problem still persists.
