### ISSUE TITLE
Testing the LaneDetection on CULane dataset  without training 

### ISSUE THREAD

**Issue by aghari19** [voldemortX/pytorch-auto-drive#130]
Hello, 

I would like to just test the CULane dataset with the curve modeling algorithm to see how it performs. Do I have to train before I run the --test? 

Please let me know, because I am doing a comparison for a class project and do not have access to GPUs or CUDA library. 

Thanks, 
Haritha

**Comment by voldemortX** [comment]
@aghari19 You can just download pre-trained weights in [MODEL_ZOO](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/MODEL_ZOO_J.md). There is no need for training.

**Comment by aghari19** [comment]
@voldemortX Thank you for letting me know about it. I have downloaded the pre-trained weights however, I am having trouble with running the algorithm with it. Could you let me know how to run with the pre-trained weights

**Comment by aghari19** [comment]
I have a follow up question: I was able to successfully able to run this command 
python main_landet.py --test --config=configs/lane_detection/baseline/vgg16_culane.py --mixed-precision

At the end it said it created the 'tb_logs' file. However, when I grep for this file it is not found. I am not sure what the output of this command would be because I would like to visualize after the images with the lanes detected. So I was thinking this command would take in a folder of images and output various .txt files with the lanes corresponding to each image. 

Then I could use the visualizer to see the lanes detected. Is my understanding incorrect?  

Please let me know, 
Thanks

**Comment by voldemortX** [comment]
@aghari19 the tb_logs are tensorboard logs mainly used for training. The predicted results are in `./output`.

You could also checkout our visualization tools in https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/VISUALIZATION.md

**Comment by voldemortX** [comment]
The problem seems to be solved. Feel free to comment or open new issues.
