### ISSUE TITLE
training environment

### ISSUE THREAD

**Issue by Zengtz** [voldemortX/pytorch-auto-drive#132]
Is the training and running environment of the code Windows or Ubuntu, and if it is, what is the version of Ubuntu?Can someone answer that?

**Comment by voldemortX** [comment]
@Zengtz It is Linux by default.  Windows may also work but is not recommended.

**Comment by voldemortX** [comment]
As for ubuntu version, all our test environments are above ubuntu 16.

If you have lower versions but can install all the dependencies, it should be fine.

**Comment by Zengtz** [comment]
> As for ubuntu version, all our test environments are above ubuntu 16.
> 
> If you have lower versions but can install all the dependencies, it should be fine.

OK,think you for your answer，I'll try your plan

**Comment by voldemortX** [comment]
Closed inactive issue. Feel free to comment or open new issues.
