### ISSUE TITLE
About the model size

### ISSUE THREAD

**Issue by huanFigure** [voldemortX/pytorch-auto-drive#134]
Hello:
Your paper is very good, but I have a question about the size of the model parameters in your experiment, the baseline (resnet-101) size is 43.56 ,but the RESA(ResNet-101) is just 31.46, and LaneATT(ResNet-122) size is 8.55? and the pretrained resnet-18 is 44.7M, RESA(Res18) is only 6.61M,

**Comment by voldemortX** [comment]
@huanFigure It is because lots of papers like resa only use stage3 of reset feature.

**Comment by voldemortX** [comment]
@huanFigure As for LaneATT, resnet122  is a special architecture, which has very few parameters.
