### ISSUE TITLE
[Bug] culane_py error at a specific case

### ISSUE THREAD

**Issue by PannenetsF** [voldemortX/pytorch-auto-drive#135]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/45866836/219528432-47a384d4-1d51-412d-99a0-cf4016fdcffc.png">

Args ars listed below. Which causes python backend not work.

```python
[[733.0, 734.0, 735.0, 736.0, 739.0, 740.0, 740.0, 738.0, 739.0, 740.0, 741.0, 742.0, 743.0, 744.0, 745.0, 745.0, 744.0, 745.0, 744.0, 744.0, 742.0, 745.0, 745.0, 747.0, 747.0, 747.0, 748.0, 745.0, 747.0, 745.0, 746.0, 745.0, 747.0, 763.0, 763.0, 763.0, 764.0, 765.0, 780.0, 777.0, 765.0], [281.0, 289.0, 298.0, 307.0, 314.0, 322.0, 322.0, 329.0, 336.0, 343.0, 351.0, 364.0, 372.0, 379.0, 387.0, 393.0, 400.0, 408.0, 417.0, 425.0, 433.0, 442.0, 450.0, 457.0, 466.0, 474.0, 482.0, 490.0, 497.0, 504.0, 512.0, 520.0, 529.0, 529.0, 540.0, 547.0, 555.0, 562.0, 568.0, 576.0, 582.0]] 
0 
50 
(3, 40)
```

**Comment by voldemortX** [comment]
@PannenetsF Thanks for pointing that out, I will look into it later today.

**Comment by voldemortX** [comment]
@PannenetsF It could be the same problem as in https://github.com/karstenBehrendt/unsupervised_llamas/pull/15

**Comment by PannenetsF** [comment]
Thanks for the reply! The only reason I used the culane_py is that it could be integrated to my script easily. For now I would turn to a python wrapper of the cpp version.&nbsp;


Thank you and I would close this issue.



---Original---
From: "Zhengyang ***@***.***&gt;
Date: Fri, Feb 17, 2023 11:29 AM
To: ***@***.***&gt;;
Cc: "Yunqian ***@***.******@***.***&gt;;
Subject: Re: [voldemortX/pytorch-auto-drive] [Bug] culane_py error at aspecific case (Issue #135)




 
@PannenetsF It could be the same problem as in karstenBehrendt/unsupervised_llamas#15

**Comment by PannenetsF** [comment]
> ```python
> [[733.0, 734.0, 735.0, 736.0, 739.0, 740.0, 740.0, 738.0, 739.0, 740.0, 741.0, 742.0, 743.0, 744.0, 745.0, 745.0, 744.0, 745.0, 744.0, 744.0, 742.0, 745.0, 745.0, 747.0, 747.0, 747.0, 748.0, 745.0, 747.0, 745.0, 746.0, 745.0, 747.0, 763.0, 763.0, 763.0, 764.0, 765.0, 780.0, 777.0, 765.0], [281.0, 289.0, 298.0, 307.0, 314.0, 322.0, 322.0, 329.0, 336.0, 343.0, 351.0, 364.0, 372.0, 379.0, 387.0, 393.0, 400.0, 408.0, 417.0, 425.0, 433.0, 442.0, 450.0, 457.0, 466.0, 474.0, 482.0, 490.0, 497.0, 504.0, 512.0, 520.0, 529.0, 529.0, 540.0, 547.0, 555.0, 562.0, 568.0, 576.0, 582.0]] 
> ```

Sorry, I just miss this reply yesterday. 

The pr fixed this issue!
