### ISSUE TITLE
How to validate the BezierLaneNet on Cityscapes?

### ISSUE THREAD

**Issue by liyfjohn** [voldemortX/pytorch-auto-drive#137]
你好，感谢分享。
请问如果想在Cityscapes上验证lanenet的效果，我应该如何去做？
谢谢！

**Comment by voldemortX** [comment]
@liyfjohn 可以尝试使用cityscapes的图片直接推理可视化。但因为没有相关标注，是不可能进行训练或指标测试的，且使用其他数据集训练的模型进行推理，效果很难保证。

**Comment by liyfjohn** [comment]
谢谢您的解答！
我在运行时遇到如下错误：

ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/stark/miniconda3/lib/python3.9/site-packages/torch/_six.py)

我的torch版本为1.12.1
请问如何解决？谢谢！

**Comment by voldemortX** [comment]
> 谢谢您的解答！
> 我在运行时遇到如下错误：
> 
> ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/stark/miniconda3/lib/python3.9/site-packages/torch/_six.py)
> 
> 我的torch版本为1.12.1
> 请问如何解决？谢谢！

看起来你需要低版本torch，试试1.8以下？

**Comment by liyfjohn** [comment]
好的，谢谢！

**Comment by voldemortX** [comment]
This issue should be addressed by #141. You can now try pytorch >= 1.8.
