### ISSUE TITLE
如何找到各个模块的代码位置

### ISSUE THREAD

**Issue by OwenTan1** [voldemortX/pytorch-auto-drive#152]
科研小白提问，我采用resnet18_culane_aug1b.py进行训练，里面的各个模块例如backbone，name='predefined_resnet_backbone'以及下面的name='predefined_dilated_blocks'，name='FeatureFlipFusion'，name='ConvProjection_1D'这些模块的具体代码在整个项目文件的什么位置呢，感谢！

**Comment by voldemortX** [comment]
@OwenTan1 可以在整个repo文件夹里面全局搜索 class xxx, def xxx

**Comment by OwenTan1** [comment]
非常感谢！

**Comment by OwenTan1** [comment]
问题已解决
