### ISSUE TITLE
Tusimple测试出现文件名不匹配

### ISSUE THREAD

**Issue by bjzhb666** [voldemortX/pytorch-auto-drive#153]
我在运行resnet34_bezierlanenet_tusimple-aug1b.sh脚本后，训练没有问题，但是运行测试代码的时候，出现了以下报错
```bash
python main_landet.py --test --config=configs/lane_detection/bezierlanenet/resnet34_tusimple_aug1b.py
```
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/71651717/3c564796-d975-4ba0-a86c-191d1512d68a)

我查看output文件夹下，文件名如下
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/71651717/9a6935b5-3ef4-4112-b5f4-729246f58d29)
请问这个问题应该怎么解决呢？是代码的问题还是我操作的问题呢？谢谢

**Comment by voldemortX** [comment]
@bjzhb666 这是个bug。你可以改一下测试脚本让它先用...._aug2.json测

**Comment by voldemortX** [comment]
> 感谢回复，更新最新代码运行了一下，训练没有问题，测试还有bug，还是文件名的问题，缺少了一个/，应该怎么修改代码呢？文件已经放到了正确位置train_set/test_label.json
> ![image](https://github.com/voldemortX/pytorch-auto-drive/assets/71651717/ace602e4-36c9-4682-9f39-4b2ebd97fc04)
> 

发一下你的autotest_tu simple.sh?

**Comment by bjzhb666** [comment]
> > 感谢回复，更新最新代码运行了一下，训练没有问题，测试还有bug，还是文件名的问题，缺少了一个/，应该怎么修改代码呢？文件已经放到了正确位置train_set/test_label.json
> > ![image](https://user-images.githubusercontent.com/71651717/260874449-ace602e4-36c9-4682-9f39-4b2ebd97fc04.png)
> 
> 发一下你的autotest_tu simple.sh?

感谢回复，找到问题所在，就是这个sh脚本中定义数据集路径缺少了一个/，已经测试成功
