### ISSUE TITLE
关于贝塞尔曲线的源码

### ISSUE THREAD

**Issue by Albertchamberlain** [voldemortX/pytorch-auto-drive#159]
请问论文的源代码有开源吗，我没有在这个仓库中找到，可否给个代码地址?

**Comment by Albertchamberlain** [comment]
这是你们的工作吗 https://github.com/mo-vic/BezierLaneNet

**Comment by voldemortX** [comment]
@Albertchamberlain 可以看一下readme。所有相关方法都有实现。

**Comment by Albertchamberlain** [comment]
> @Albertchamberlain 可以看一下readme。所有相关方法都有实现。

好的，谢谢

**Comment by Albertchamberlain** [comment]
Readme中好像只有训练的代码，我指的是贝塞尔的model，loss，backbone这种好像没找到

**Comment by voldemortX** [comment]
> Readme中好像只有训练的代码，我指的是贝塞尔的model，loss，backbone这种好像没找到

你可以在config文件里看到这些组件的类名

**Comment by Albertchamberlain** [comment]
ok，谢谢，我找到了
