### ISSUE TITLE
关于贝塞尔ground truth生成的问题

### ISSUE THREAD

**Issue by mmpp406** [voldemortX/pytorch-auto-drive#160]
请问下作者这里的论文，下标值不应该是从0开始吗，为啥是从1开始呢？看的时候有一点点小疑惑
![image](https://github.com/voldemortX/pytorch-auto-drive/assets/65806430/3331bce6-b956-46ff-99d3-807c9c3df0f0)

**Comment by voldemortX** [comment]
> 请问下作者这里的论文，下标值不应该是从0开始吗，为啥是从1开始呢？看的时候有一点点小疑惑
> ![image](https://github.com/voldemortX/pytorch-auto-drive/assets/65806430/3331bce6-b956-46ff-99d3-807c9c3df0f0)
> 

感谢指出，看起来可能是个typo

**Comment by mmpp406** [comment]
了解了
