### ISSUE TITLE
分割图可视化

### ISSUE THREAD

**Issue by 1171000410** [voldemortX/pytorch-auto-drive#171]
您好，
scnn模型是基于语义分割的，但是我使用--pred可视化之后，出来的是一系列点。
请问我怎么可视化分割图呀？
（我也注意到了教程中的--mask-path，但是这个参数似乎要指定seg label的路径？有点没太明白，希望您能帮忙解答一下）

谢谢！

**Comment by voldemortX** [comment]
#170 你是不是和这个是一个需求

**Comment by voldemortX** [comment]
closed for duplication.
