### ISSUE TITLE
train

### ISSUE THREAD

**Issue by miao02830** [voldemortX/pytorch-auto-drive#34]
when i train 
i meet a problem 

![image](https://user-images.githubusercontent.com/27732256/139366727-8bd138eb-31eb-4684-bc38-c1a883e2c9a8.png)
![image](https://user-images.githubusercontent.com/27732256/139366748-2642d558-d9e6-49ce-8c69-775e98cfd4c1.png)

I saw on the Internet that it may be a multi-threaded problem. I had encountered this situation before I could only run one round. Later, I changed the number of workers to 1. Now I ran three rounds and encountered this problem again.

i'm confused about this question. thank you for your help!

**Comment by voldemortX** [comment]
@miao02830 This issue happened a long time ago. Please open a new issue if the problem continues to show up in the new master branch.
