### ISSUE TITLE
Sugggestion: Missing `requirements.txt` file. 

### ISSUE THREAD

**Issue by kalkun** [voldemortX/pytorch-auto-drive#37]
The installation instructions describe installing generally the packages: 
```bash
pip install tqdm ujson tensorboard imageio opencv-python pyyaml thop Shapely p-tqdm scipy sklearn filetype
```

However, in doing so I get an error when simply trying to run: 
```bash
python main_landec.py --help
Traceback (most recent call last):
  File "main_landec.py", line 11, in <module>
    from utils.losses import LaneLoss, SADLoss, HungarianLoss
  File "app/pytorch-auto-drive/utils/__init__.py", line 1, in <module>
    from . import datasets
  File "app/pytorch-auto-drive/utils/datasets/__init__.py", line 3, in <module>
    from .tusimple import *
  File "app/pytorch-auto-drive/utils/datasets/tusimple.py", line 5, in <module>
    from .utils import LaneKeypointDataset
  File "app/pytorch-auto-drive/utils/datasets/utils.py", line 5, in <module>
    from torch._six import container_abcs, string_classes, int_classes
ImportError: cannot import name 'container_abcs' from 'torch._six' (/opt/conda/lib/python3.8/site-pack
ages/torch/_six.py)
```

which at least to me indicates that the installed version of `torch` differs from the intended version and could perhaps be alleviated by specifying the exact version of the required packages.

**Comment by voldemortX** [comment]
Yes, you are right! We'll try add a requirements.txt in Q4.

The currently tested version is torch1.6.0cu102 and torch1.3.0cu90.

**Comment by voldemortX** [comment]
We do intend to support all pytorch version over 1.6, this seems to be a BC-Break from torch1.9

**Comment by Zeleni9** [comment]
Hey, is the repo supporting torch > 1.6.0 ? THe only issue it seems is this import: 

`from torch._six import container_abcs, string_classes, int_classes`

Thank you.

**Comment by voldemortX** [comment]
@Zeleni9 It supports up to pt1.8.  These lines are not supported any more in pytorch 1.9. Maybe we can do a version check and workaround here.

**Comment by Zeleni9** [comment]
Yea I saw that I need:
-  torch >= 1.6 <= 1.8.0 
- torchvision >= 0.7.0 <= 0.9.0

and it works for me.
