### ISSUE TITLE
Evaluate  with official scripts. openCV bug

### ISSUE THREAD

**Issue by hzzzzjzyq** [voldemortX/pytorch-auto-drive#46]
(scnn2) zzj@zzj-OMEN-25L-Desktop-GT12-1xxx:/mnt/data/pycharmmm/pytorch-auto-drive/tools/culane_evaluation$ make
CXX src/evaluate.cpp
In file included from include/lane_compare.hpp:4:0,
                 from include/counter.hpp:4,
                 from src/evaluate.cpp:8:
include/spline.hpp:6:10: fatal error: opencv2/core/core.hpp: No such file or directory
 #include <opencv2/core/core.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40：build/src/evaluate.o] error

i have install requirement.txt with opencv-python. do i need to install other opencv?

**Comment by voldemortX** [comment]
@hzzzzjzyq Yes, you do need the cpp opencv for the official evaluation scripts since they are in cpp. The existing python scripts do not perfectly align with the official scripts, we might use them for visualization later but the evaluation will remain cpp.

**Comment by hzzzzjzyq** [comment]
thank you very much !



---Original---
From: "Zhengyang ***@***.***&gt;
Date: Thu, Dec 2, 2021 10:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [voldemortX/pytorch-auto-drive] Evaluate  with official scripts.openCV bug (Issue #46)




 
@hzzzzjzyq Yes, you do need the cpp opencv for the official evaluation scripts since they are in cpp. The existing python scripts do not perfectly align with the official scripts, we might use them for visualization later but the evaluation will remain cpp.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by voldemortX** [comment]
You're welcome. I'll close this for now, feel free to reopen if you encounter further opencv problems.

**Comment by hzzzzjzyq** [comment]
(scnn2) zzj@zzj-OMEN-25L-Desktop-GT12-1xxx:/mnt/data/pycharmmm/pytorch-auto-drive/tools/culane_evaluation$ make
CXX/LD evaluate
/usr/bin/ld: build/src/evaluate.o: undefined reference to symbol '_ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi'
/usr/bin/ld: /lib/x86_64-linux-gnu/libopencv_imgcodecs.so.4.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:44：evaluate] 错误 1

i have install cpp opencv ,there is a error when i cd tools/culane_evaluation to make

**Comment by voldemortX** [comment]
@hzzzzjzyq Are you using windows and OpenCV > 3? Try delete line 20-22: https://github.com/voldemortX/pytorch-auto-drive/blob/eed417ff0fef46118cab310e69563358bf714b28/tools/culane_evaluation/Makefile#L20

**Comment by hzzzzjzyq** [comment]
thank you, i use ubuntu20

**Comment by voldemortX** [comment]
If it fails, try replace the three lines with `LIBRARIES += opencv_imgcodecs`

**Comment by voldemortX** [comment]
One of the two ways should suffice. It is probably because your system's OpenCV installation could not be detected.

**Comment by hzzzzjzyq** [comment]
i try LIBRARIES += opencv_imgcodecs

/usr/bin/ld: build/src/lane_compare.o: in function `LaneCompare::get_lane_similarity(std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&)':
lane_compare.cpp:(.text+0x600): undefined reference to `cv::_InputArray::_InputArray(cv::MatExpr const&)'
/usr/bin/ld: build/src/lane_compare.o: in function `cv::MatExpr::operator cv::Mat() const':
lane_compare.cpp:(.text._ZNK2cv7MatExprcvNS_3MatEEv[_ZNK2cv7MatExprcvNS_3MatEEv]+0x28): undefined reference to `cv::Mat::Mat()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:45：evaluate] 错误 1

**Comment by voldemortX** [comment]
@hzzzzjzyq That is weird. What is your OpenCV version?

**Comment by voldemortX** [comment]
Maybe try directly using my built file [here](https://drive.google.com/file/d/1czPD3K9L7jyBVWwyRke36opjzydeYAgo/view?usp=sharing).

**Comment by hzzzzjzyq** [comment]
Thank you for your generous help！

**Comment by Auroradsy** [comment]
I have already installed the Opencv for C++(I can check the version of it, as you can see on the picture below), and successfully 'make', finished predict and saved lanes, but during my way to evaluate the test set with official scripts, I met this problem.
![1](https://user-images.githubusercontent.com/50282763/147542768-408bffa6-1644-4501-8baf-19d4ae0e38d2.jpg)
![2](https://user-images.githubusercontent.com/50282763/147542788-c845b6f2-3329-4e46-a96a-0602dffea049.jpg)

**Comment by voldemortX** [comment]
@Auroradsy It seems you have opencv installation issues. Maybe it's wrong/mixed versions?

**Comment by Auroradsy** [comment]
> @Auroradsy It seems you have opencv installation issues. Maybe it's wrong/mixed versions?
> 
> I suspect your current linked version of opencv is not the same as the version that was used to make

Thanks, I'll get a double check, but I want to know that which version is exactly I need to install, I just installed 3.4.16 and is it a good choice?

**Comment by Auroradsy** [comment]
> @Auroradsy It seems you have opencv installation issues. Maybe it's wrong/mixed versions?
> 
> I suspect your current linked version of opencv is not the same as the version that was used to make

BTW, how can I check the version that I used for make? And which version I linked currently?

**Comment by voldemortX** [comment]
> > @Auroradsy It seems you have opencv installation issues. Maybe it's wrong/mixed versions?
> > 
> > I suspect your current linked version of opencv is not the same as the version that was used to make
> 
> BTW, how can I check the version that I used for make? And which version I linked currently?

Hi, I use 3.2.0. And it seems your system is also searching for 3.2 in the screen shot? You can check version by:

```
pkg-config --modversion opencv
```

**Comment by voldemortX** [comment]
For those who have opencv issues, we now have a python backend for CULane eval, which does not require compiling with opencv anymore!

However, the eval precision is not perfectly aligned, although I tried my best to align the LaneATT's python version to official cpp version.

Some general tips for cpp version users:

**OpenCV2/3** can follow the current documentation.

**OpenCV4 and above** needs to set CXXFLAGS like in https://github.com/voldemortX/pytorch-auto-drive/issues/80#issuecomment-1109935902

**Make sure you have only one OpenCV version on your machine! Including self-installed and ubuntu packages.**
