### ISSUE TITLE
How to improve the accuracy of lane detection model？

### ISSUE THREAD

**Issue by daigang896** [voldemortX/pytorch-auto-drive#50]
Hello. Can the RESA method use erfnet as the backbone? In addition to increasing the input size of the model, can SCNN or RESA use some techniques to improve the accuracy?
At present, it is found that the generalization performance of these methods is not good, and it feels that the model does not know what lane line is.

**Comment by voldemortX** [comment]
@daigang896 I'm guessing you are using a custom dataset, I can't say much without more knowledge. Segmentation method should be the most robust (pure bottom-up), however, **if and only if** you are in an ego-lane task (can restrict prediction to a fixed and meaningful maximum number of classes). For general info, you can check these:

0. Check the code. e.g., are your labels loaded correct?
1. Did you fully trained the models? Try match the final loss to a public dataset with similar difficulty level (e.g., TuSimple)
2. Are your lane classes meaningful and is that meaning consistent across images? i.e., do they have specific meanings like ego-left, ego-right, etc. If that can't be managed, maybe general methods like LSTR is better suited.
3. The only optimization you can do for seg methods would be adjusting lr, epoch, warmup length, usually the resnet34 backbone is enough.

For RESA-ERFNet, you'll be able to easily use any backbones available after #45 is merged. Before that, you can hack into the code yourself similar to SCNN-ERFNet.

**Comment by voldemortX** [comment]
FYI, the input size may not be crucial. Lane detection don't rely on that as much as typical semantic segmentation.

**Comment by daigang896** [comment]
@voldemortX  Well, I understand something. Thank you very much for your explanation.

**Comment by voldemortX** [comment]
You're welcome.

**Comment by voldemortX** [comment]
It seems this issue is resolved, I'll close for now. Feel free to reopen.
