### ISSUE TITLE
loss曲线不收敛

### ISSUE THREAD

**Issue by zhj695918236** [voldemortX/pytorch-auto-drive#52]
您好，请问一下为什么我通过tensorboard查看的loss曲线下降并未收敛?（resnet101_scnn_culane）。（其他网络也是如此）。感谢解答！
![6B40E73875809D90416C17BA5875EEE5](https://user-images.githubusercontent.com/67667915/148636601-10d0192f-b82a-4694-83f6-097a309bb540.jpg)
。

**Comment by voldemortX** [comment]
@zhj695918236 你好，不收敛具体指的是？这些曲线看起来已经下降到了一个足够低的loss水平，对于大多数模型更长的训练时间确实有可能带来更低的loss值，但这通常并不会带来进一步的泛化能力提升 （aka 更高的测试/验证集结果）。

**Comment by zhj695918236** [comment]
好的，谢谢！但是loss并未收敛，是否可以认为模型还有提升的空间？但是看着曲线的走势，应该是无法收敛！

**Comment by voldemortX** [comment]
> 好的，谢谢！但是loss并未收敛，是否可以认为模型还有提升的空间？但是看着曲线的走势，应该是无法收敛！

嗯训练集没到100%，所以理论空间总是有的

**Comment by zhj695918236** [comment]
谢谢解答！请问大佬这次更新对之前的配置是否有影响？我发现shell命令变了，并且我无法找到之前的shell命令。大佬能否提供一份之前的shell脚本。感谢！

**Comment by voldemortX** [comment]
> 谢谢解答！请问大佬这次更新对之前的配置是否有影响？我发现shell命令变了，并且我无法找到之前的shell命令。大佬能否提供一份之前的shell脚本。感谢！

你可以使用git checkout 回退版本

**Comment by zhj695918236** [comment]
好的，谢谢

**Comment by voldemortX** [comment]
It seems this issue is resolved, I'll close for now. Feel free to reopen.
