### ISSUE TITLE
Visualization for the LLAMAS dataset

### ISSUE THREAD

**Issue by AirSmoke031** [voldemortX/pytorch-auto-drive#58]
Hello. its me again.

I managed to visualize data for the CULane and TuSimple dataset.  However I ran into trouble trying to do so for the LLAMAS dataset.

First thing I did is python main_landet.py --test --config=configs/lane_detection/scnn/vgg16_llamas.py --mixed-precision using a pretrained model. It generated the test folder in the output file which contains 2 folders (one is "images-2014-12-22-13-22-35_mapping_280S_2nd_lane") and inside of it there are .txt files with the predicted lane points (1419283522_0012893000.lines.txt).

I understand that it is the CULane format and to generate visualization images I should be able to do it like with CULane.
So I ran this, 
python tools/vis/lane_img_dir.py --image-path=/home/grgur/LLAMAS/color_images/test/images-2014-12-22-13-22-35_mapping_280S_2nd_lane --keypoint-path=/home/grgur/pytorch-auto-drive/output/test/images-2014-12-22-13-22-35_mapping_280S_2nd_lane --image-suffix=.png --keypoint-suffix=.lines.txt  --save-path=PAD_test_images/lane_test_images/LLAMAS_res/vgg16_llamas --config=/home/grgur/pytorch-auto-drive/configs/lane_detection/scnn/vgg16_llamas.py 

And the error is 
FileNotFoundError: [Errno 2] No such file or directory: '/home/grgur/pytorch-auto-drive/output/test/images-2014-12-22-13-22-35_mapping_280S_2nd_lane/1419283522_0012893000_color_rect.lines.txt'

The error itself is pretty straightforward. The names of the generated .txt files do not end with color_rect but only with lines.
However, thats the way they are generated. I tried to change the name and add "rect_lines" to the generated .txt files in the output folder and ran the script again. The error then would be the next file in the folder. So the generated names of the output txt files dont add up to the required.

Any thoughts?

**Comment by voldemortX** [comment]
What about changing the --image-suffix to find a common prefix for the png and txt?

**Comment by AirSmoke031** [comment]
I changed in the lane_det_tester in the runners to file_path = filenames[j].replace("_color_rect", "_color_rect") instead of file_path = filenames[j].replace("_color_rect", ""). I know its a simpleton solution but It now generates the predicted lane point .txt files with the same name. Its still testing but its generating with the same name.
I will try to visualize later then I will come back to you .

**Comment by AirSmoke031** [comment]
Whelp, new error when I try to visualize.
(voldemort) grgur@MCS90:~/pytorch-auto-drive$ python tools/vis/lane_img_dir.py --image-path=/home/grgur/LLAMAS/color_images/test/images-2014-12-22-13-22-35_mapping_280S_2nd_lane --keypoint-path=/home/grgur/pytorch-auto-drive/output/test/images-2014-12-22-13-22-35_mapping_280S_2nd_lane --image-suffix=.png --keypoint-suffix=.lines.txt  --save-path=PAD_test_images/lane_test_images/LLAMAS_res/vgg16_llamas --config=/home/grgur/pytorch-auto-drive/configs/lane_detection/scnn/vgg16_llamas.py 
  0%|                                                                                                                                                                              | 0/140 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3732818) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/vis/lane_img_dir.py", line 71, in <module>
    runner.run()
  File "/home/grgur/pytorch-auto-drive/utils/runners/lane_det_visualizer.py", line 111, in run
    for imgs, original_imgs, targets in tqdm(self.dataloader):
  File "/home/grgur/.local/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()
  File "/home/grgur/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 3732818) exited unexpectedly

**Comment by AirSmoke031** [comment]
Reduced the number of workers in config file, now it works.

**Comment by voldemortX** [comment]
@AirSmoke031 That's great! I'll try and determine an elegant way to visualize on LLAMAS later this week. Currently I'm kind of busy with papers.

**Comment by voldemortX** [comment]
@AirSmoke031 I can manage to visualize on LLAMAS by `--image-suffix=_color_rect.png` without changing the code.

**Comment by voldemortX** [comment]
This issue seems to be addressed by specifying runtime args, I'll close it for now. Feel free to reopen.
