### ISSUE TITLE
How can we Inference the BezierLaneNet model on a custom Video?

### ISSUE THREAD

**Issue by ayushmankumar7** [voldemortX/pytorch-auto-drive#65]
I am also working on using parametric curves for Lane Detection. 
I came across your paper. Really liked it! 
I wanted to test this Repo on a custom Video but the code base seems to be a bit confusing for BezierLaneNet. :( 
Again, I am very comfortable in **Pytorch** but then I saw that you also used **mmcv** for some part of the code - "DCN_v2_Ref" in feature_flip_fusion.py.

**Comment by voldemortX** [comment]
@ayushmankumar7 Did you encounter bugs when visualizing a video?

Yes,  the use of mmcv deformable conv is unfortunate and we hope to replace it with torchvision dcn or cpp extension like LaneATT nms #55.  Also we are currently working on a cleaner architecture that do not require complex ops such as dcn or dilation.

**Comment by voldemortX** [comment]
@ayushmankumar7 FYI, this command can produce results for video:

```
python tools/vis/lane_video.py --video-path=./PAD_test_images/lane_test_images/tusimple_val_1min.avi --save-path=bln.avi --config=configs/lane_detection/bezierlanenet/resnet34_tusimple-aug1b.py --checkpoint=checkpoints/resnet34_bezierlanenet_tusimple_aug2_20211109.pt
```

You can get the weights in MODEL_ZOO.md and the video in VISUALIZATION.md.

Direct links:

Model: https://drive.google.com/file/d/1FFn8j2BoUsyj8UbBcfeGWKvCQj9Qg-44/view?usp=sharing

Video: https://drive.google.com/file/d/1XQvBS1uoHeIgUv7oDQ4Vp1tWYi0oAGhU/view?usp=sharing

However, if your custom video is very different from the training datasets, the results won't be good. Robustness of compact representation (curves) are bad when evaluated out-of-domain (assuming limited data in training datasets, which is the case for current public datasets), while bottom-up methods (segmentation) are often times better.

**Comment by ayushmankumar7** [comment]
Hey! Sorry for the late reply. 
Thanks for sharing the snippet and test data. 
Currently, I am working on Windows. 
I got some common mmcv related errors, tried debugging it, and then found that mmcv-full doesn't support Windows :) ... Sad. Will have to switch to Ubuntu to test my code.

**Comment by voldemortX** [comment]
Yes the mmcv installation and versioning can be an issue. But windows could lead to other issues as well, ubuntu seems a better choice.

**Comment by voldemortX** [comment]
The issue seems to be resolved. I'll close for now. Feel free to ask for reopen or open new issues.
