### ISSUE TITLE
Realtime lane detection

### ISSUE THREAD

**Issue by ilkeratik** [voldemortX/pytorch-auto-drive#66]
I want to apply model inferences and lanes into frames that comes from camera. And I don't really like your configs 'curse'. I don't know if it's just me but whole stuff is so complex.

**Comment by voldemortX** [comment]
@ilkeratik I also felt the complexity of configs when using mmcv based stuffs.  However, it is hard to manage multiple model architectures and various tasks without configs, and  I did a customized config system to avoid complexity to some extent. It takes  some getting used to but, many would find it useful for algorithm iteration.

For your use case, you can try build your application referencing our video visualization process.

**Comment by ilkeratik** [comment]
@voldemortX Thanks, I've never seen mmcv libs so this repo was extra weird to me :D but I will put some extra work to understand it.

**Comment by voldemortX** [comment]
> @voldemortX Thanks, I've never seen mmcv libs so this repo was extra weird to me :D but I will put some extra work to understand it. 

You are welcome.  Happy hacking!

**Comment by voldemortX** [comment]
The issue seems to be resolved. I'll close for now. Feel free to ask for reopen or open new issues.
