### ISSUE TITLE
lane_img_dir.py --pred does it support outputting keypoints txt

### ISSUE THREAD

**Issue by 514398473** [voldemortX/pytorch-auto-drive#71]
Hello, my English is not good
generate a TXT for each picture

**Comment by 514398473** [comment]
Hello, it's solved. I modified the vis_utils.py added text output.

**Comment by voldemortX** [comment]
@514398473 如果你真的需要keypoint的txt文件，culane和llamas的数据集测试推理都存的是txt。但如果你的输入是自己的图片视频之类的，那确实需要改一下code。如果你想给这个框架增加这个功能，欢迎提出PR。
