### ISSUE TITLE
unfind bezier_labels

### ISSUE THREAD

**Issue by FANG-MING** [voldemortX/pytorch-auto-drive#75]
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/CULane/bezier_labels/train_3.json'

**Comment by wht1712** [comment]
Hi, how do you solve this problem?

**Comment by voldemortX** [comment]
@wht1712 just download the labels, it's in the readmes.
https://drive.google.com/file/d/1s7N45IjUWxZEUIuyDUCIqtDfhzxRjmfL/view?usp=sharing

**Comment by wht1712** [comment]
@voldemortX Thanks!
