### ISSUE TITLE
About the data preprocessing

### ISSUE THREAD

**Issue by huanFigure** [voldemortX/pytorch-auto-drive#78]
I follow the README step by step to prepare the CULane dataset, and I have download the CULane dataset successfully. But when I perform the  'make'  in 4.Prepare official evaluation scripts  of the docs/datasets/CULANE.md ,I always get the fault about 'ln opencv_imgproc' ,which edition of the opencv ,is there someone completed the CULane dataset prepare?

**Comment by voldemortX** [comment]
@huanFigure 

If you are using opencv3, get rid of the `if` here and just keep L21. If not delete them, it should work 1 of the 2 ways.  https://github.com/voldemortX/pytorch-auto-drive/blob/ca81e992794b090dca088df7ad8defed239e24a6/tools/culane_evaluation/Makefile#L20

The process should be automatic, but sometimes your system can't get opencv version (that really happens a lot these days), and it can't be executed.

**Comment by voldemortX** [comment]
I've updated the code (removed automatic version check) to make things clear.

**Comment by huanFigure** [comment]
> 

It's worked,thank you very much

**Comment by voldemortX** [comment]
You're welcome. Since this issue is resolved, I'll close this issue for now.
