### ISSUE TITLE
inplace operation error

### ISSUE THREAD

**Issue by solidexu** [voldemortX/pytorch-auto-drive#81]
when I tested RESA with resnet50, error occurred. Then I tested SCNN resnet50, same issue

python main_landet.py --train --config=./configs/lane_detection/resa/resnet50_culane.py --mixed-precision 
Loaded torchvision ImageNet pre-trained weights V1.
Not using distributed mode
cuda
Traceback (most recent call last):
  File "main_landet.py", line 65, in <module>
    runner.run()
  File "/home/aaa/pytorch-auto-drive-master/utils/runners/lane_det_trainer.py", line 55, in run
    scaler.scale(loss).backward()
  File "/home/aaa/.local/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/aaa/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [5, 128, 36, 100]], which is output 0 of ReluBackward0, is at version 20; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by voldemortX** [comment]
@solidexu I don't have spare gpu right now. I will try test it tomorrow.

**Comment by solidexu** [comment]
I don't know why,  the issue is solved by commenting out the relu in RESAReducer. It's too STRANGE for me. 
![image](https://user-images.githubusercontent.com/52859850/165468327-60c536fe-0aca-4ebf-9cb2-19490cfc19a8.png)

**Comment by voldemortX** [comment]
> I don't know why, the issue is solved by commenting out the relu in RESAReducer. It's too STRANGE for me. ![image](https://user-images.githubusercontent.com/52859850/165468327-60c536fe-0aca-4ebf-9cb2-19490cfc19a8.png)

What pytorch version are you using & do you experience this with/without mixed precision?

**Comment by solidexu** [comment]
I use torch 1.10.2. And I have tested with/without mixed precision, same issue.

**Comment by voldemortX** [comment]
@solidexu I don't really have 1.10, but I can start training normally with 1.6.0 (I have only one card so I first changed world_size to 1 and then use only bs 2).

Here is my command:

```
python main_landet.py --train --config=./configs/lane_detection/resa/resnet50_culane.py --mixed-precision --batch-size=2
```

**Comment by voldemortX** [comment]
Are you running customized code or do you see that error in the current master branch?

**Comment by solidexu** [comment]
In current master branch， I download your new branch three days ago in fact.  Commenting out the relu also occur another error during training.  I think I can try torch 1.6.0

**Comment by voldemortX** [comment]
@solidexu Sorry to disturb, but did you solve this issue by down-grading pytorch? I think it is encountered by others as well.

**Comment by voldemortX** [comment]
close by #121
