### ISSUE TITLE
tusimple視覺可視化問題

### ISSUE THREAD

**Issue by j2856256** [voldemortX/pytorch-auto-drive#82]
您好 想請問一下
如何將tusimple test完後json檔修改為culane的格式
tusimple json 檔，內含h_samples、lanes、run_time、raw_file,若要可視化是不是只能改成像測試檔案一樣,單一圖片只有lanes的json檔

**Comment by j2856256** [comment]
![Screenshot from 2022-04-28 20-54-04](https://user-images.githubusercontent.com/103163006/165756700-d6a722d3-443d-459f-b698-ba824292bc0f.png)
tusimple json檔

**Comment by j2856256** [comment]
![Screenshot from 2022-04-28 20-55-54](https://user-images.githubusercontent.com/103163006/165756947-3db4811a-b890-432d-b78c-0e5b131df4fd.png)
測試檔案

**Comment by voldemortX** [comment]
@j2856256 I‘m assuming you speak Chinese.

你是要可视化Tusimple数据集还是你有其他数据集用了这个格式？

如果是TuSimple数据集本身是有相关的特殊支持的。虽然写成了编程教程，但是本身已经包括在了master分支： https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/advanced/VISUALIZE_LANE_DATASETS.md

如果是其他数据集用了类似的标注，或者只是普通数据输入没有数据集，你可以参照这个教程做有针对性地实现。

**Comment by j2856256** [comment]
utils/datasets/tusimple_vis.py具體要如何使用可以提供具體的執行碼嗎？

**Comment by voldemortX** [comment]
> utils/datasets/tusimple_vis.py具體要如何使用可以提供具體的執行碼嗎？

首先需要在config文件增加vis_dataset，然后才可以运行。请仔细阅读这一段：
https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/advanced/VISUALIZE_LANE_DATASETS.md#expected-usage

**Comment by j2856256** [comment]
新增後就可以了，非常感謝
那我可以再問一個問題嗎？
如何讓tusimple test資料20個fps都有輸出？

**Comment by j2856256** [comment]
添加後就可以了，非常感謝
那我可以再問一個問題嗎？
如何讓tusimple test資料20個fps都有輸出？

**Comment by j2856256** [comment]
添加後就可以了，非常感謝
那我可以再問一個問題嗎？
如何讓tusimple test全部的20fps都有輸出？

**Comment by j2856256** [comment]
添加之後就可以了，非常感謝
那我可以再問一個問題嗎？ 如何讓tusimple test全部都有輸出，因為該作法只有第20個fps有結果

**Comment by j2856256** [comment]
如何讓tusimple 全部test資料都有輸出，因為該作法只有第20個fps有結果

**Comment by voldemortX** [comment]
> 如何讓tusimple 全部test資料都有輸出，因為該作法只有第20個fps有結果

你指的是tusimple测试时产生的json文件么，那里面的fps都是不做测试的。速度测试有专用的脚本:

https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/BENCHMARK.md#profiling-models-yourself

**Comment by voldemortX** [comment]
The issue seems to be resolved. I'll close for now. Feel free to ask for reopen or open new issues.
---
本issue已基本解决，暂时关闭。如果有进一步的疑惑，可以随时reopen或者开新的。
