### ISSUE TITLE
error：from utils import datasets

### ISSUE THREAD

**Issue by 578223592** [voldemortX/pytorch-auto-drive#85]
when i read the code ，i get some codes in `utils>runners>base.py` from about lines 80

```python
    def get_dataset_statics(self, dataset, map_dataset_statics, exist_ok=False):
        assert hasattr(self, '_cfg')
        if map_dataset_statics is not None:
            for k in map_dataset_statics:
                if exist_ok and k in self._cfg.keys():
                    continue
                if isinstance(dataset, str):
                    from utils import datasets
                    attr = getattr(datasets.__dict__[dataset], k)
                else:
                    attr = getattr(dataset, k)
                self._cfg[k] = attr
```

i want to see `datasets.__dict__` so i write a `py` file in the same directory as `base.py`.

```python
from utils import datasets
dict=datasets.__dict__
print(dict)
```

output:

```bash
/home/swx/.conda/envs/pad/bin/python /home/swx/pytorch-auto-drive-master/utils/runners/temp.py
Traceback (most recent call last):
  File "/home/swx/pytorch-auto-drive-master/utils/runners/temp.py", line 2, in <module>
    from utils import datasets
ModuleNotFoundError: No module named 'utils'
```

I tried to change the code to:

```python
import sys
import os
sys.path.append(os.path.join(os.getcwd()))
from utils import datasets
dict=datasets.__dict__
data=datasets
print(dict)
```

and there is no error like :`ModuleNotFoundError: No module named 'utils'` anymore. I don't know if this is a bug or if I misunderstood.

In addition, I would appreciate it if I could get the function's action of `get_dataset_statics`

**Comment by voldemortX** [comment]
@578223592 what's the `pwd` when you run that `temp.py`? You need to import according to your execution directory.

**Comment by voldemortX** [comment]
what do you mean exactly by the function's action of `get_dataset_statics`? Do you mean you want me to explain what this function does or something?

**Comment by 578223592** [comment]
Thank you very much. Your recommendation is very helpful.


> @578223592 what's the `pwd` when you run that `temp.py`? You need to import according to your execution directory. If no proper import is available, I do recommend using importmagician for sys path appends (like in the configs), it is cleaner.
