### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by wht1712** [voldemortX/pytorch-auto-drive#87]
Thanks for the awesome bezier lane detection work.
When i use the fcns.get_control_points to generate my own control points, i got the problem "numpy.linalg.LinAlgError: SVD did not converge", do you know the reason? Waiting for your reply, thanks!

**Comment by voldemortX** [comment]
@wht1712 I don't recall encountering the same error.  Do you have input details to repoduce the issue?

**Comment by wht1712** [comment]
@voldemortX Sorry to bother you, i have found the bug. Thanks for your quick reply again!
