### ISSUE TITLE
sad code

### ISSUE THREAD

**Issue by miao02830** [voldemortX/pytorch-auto-drive#88]
When will the sad code go online，pls~ths

**Comment by voldemortX** [comment]
@miao02830 Do you mean SAD? I'm afraid it won't happen for a long period of time, because we can't reproduce it. See https://github.com/voldemortX/pytorch-auto-drive/wiki/Notes 7. Why SAD implementation is indefinitely postponed?

**Comment by miao02830** [comment]
ok,thank you for your replay
