### ISSUE TITLE
Link to my repo request!

### ISSUE THREAD

**Issue by mo-vic** [voldemortX/pytorch-auto-drive#91]
Hi, Zhengyang, I'm so glad to read the paper, excellent work here~, and btw, I wondering if you could add a little link to my [BezierLaneNet](https://github.com/mo-vic/BezierLaneNet) repo, though out-of-date, it can also serve as complementary material, thx:smile:

**Comment by voldemortX** [comment]
@mo-vic Your work was also great! And I've already discussed it in the wiki page:

https://github.com/voldemortX/pytorch-auto-drive/wiki/Notes

I'll later direct people to it in https://github.com/voldemortX/pytorch-auto-drive/tree/master/configs/lane_detection/bezierlanenet

**Comment by mo-vic** [comment]
thanks again:smile:, hope this idea could provide an alternative to academic research and industrial:star:

**Comment by voldemortX** [comment]
I hope the same thing. Fingers crossed!
