### ISSUE TITLE
关于UFLD模型

### ISSUE THREAD

**Issue by miao02830** [voldemortX/pytorch-auto-drive#93]
您好，请问您提供的ufld模型可以训练culane数据集吗？没有看到关于culane的配置文件。您训练过吗，是否正常？我用原作者提供的代码，训练culane数据集得到权重，用训练的权重做测试，生成的lines.txt都是空的。谢谢您。

**Comment by voldemortX** [comment]
> 您好，请问您提供的ufld模型可以训练culane数据集吗？没有看到关于culane的配置文件。您训练过吗，是否正常？我用原作者提供的代码，训练culane数据集得到权重，用训练的权重做测试，生成的lines.txt都是空的。谢谢您。

我们的repo里没有ufld。我也没有跑过它的训练。但我听说laneatt的作者跑过ufld的tusimple是可以跑通的，但点数好像略低了一点点。我觉得官方代码应该是可用的，ufld作者提供culane支持了吧应该？
